# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/mnist.proto
# Protobuf Python Version: 4.25.7
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11model/mnist.proto\x12\x04main\",\n\x0bImageSample\x12\r\n\x05label\x18\x01 \x01(\x05\x12\x0e\n\x06pixels\x18\x02 \x03(\x02\"-\n\x07\x44\x61taset\x12\"\n\x07samples\x18\x01 \x03(\x0b\x32\x11.main.ImageSampleB\x13Z\x11./backend/mnistpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model.mnist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021./backend/mnistpb'
  _globals['_IMAGESAMPLE']._serialized_start=27
  _globals['_IMAGESAMPLE']._serialized_end=71
  _globals['_DATASET']._serialized_start=73
  _globals['_DATASET']._serialized_end=118
# @@protoc_insertion_point(module_scope)
